/**
 * Public API descriptions shown in the documentation and generated LLM data.
 * Keep these short, concrete, and written from the user's point of view.
 */
const common = {
  disabled: "是否禁用组件。",
  asChild: "是否将组件渲染为唯一的子元素，并将组件的属性和事件传递给该子元素。",
}

export const PropDescriptions: Record<string, Record<string, string>> = {
  "ai-prompt": {
    size: "输入框的尺寸密度。compact 适合紧凑布局，default 为标准尺寸。",
  },
  "ai-conversation-timeline": {
    items: "按对话发生顺序排列的轮次数据。",
    activeId: "当前激活轮次的受控 ID。",
    defaultActiveId: "非受控模式下初始激活轮次的 ID。",
    previewSide: "悬停预览卡片显示在时间线的哪一侧。",
    preview: "是否显示悬停预览卡片。",
    onActiveChange: "时间线标记变为激活状态时触发。",
    onNavigate: "用户选择某个时间线标记时触发。",
  },
  "ai-tool": {
    status: "工具调用的当前状态，例如执行中、成功或失败。",
    ...common,
  },
  "ai-stream": {
    children: "已经接收到的完整文本内容。",
    isStreaming: "是否仍在接收后续文本。",
    featherLength: "实时渐隐效果覆盖的末尾字符数量。",
  },
  markdown: {
    children: "要解析并渲染的 Markdown 源文本。",
    isStreaming: "源文本是否仍在接收后续内容。",
    featherLength: "流式羽化效果覆盖的末尾字符数量。",
    components: "覆盖指定 Markdown 元素的 React 渲染器。",
    allowElement: "根据元素、位置和父节点决定是否保留当前元素。",
    allowedElements:
      "只允许渲染的 HTML 元素名称。不能与 disallowedElements 同时使用。",
    disallowedElements:
      "不允许渲染的 HTML 元素名称。不能与 allowedElements 同时使用。",
    remarkPlugins: "追加在内置 GFM 支持之后的 remark 插件。",
    rehypePlugins: "处理解析后 HTML 抽象语法树的 rehype 插件。",
    remarkRehypeOptions: "传递给 remark-rehype 的转换选项。",
    skipHtml: "是否完全忽略 Markdown 中的原始 HTML。",
    unwrapDisallowed: "是否保留被过滤元素的子内容，而只移除元素本身。",
    urlTransform: "在链接或图片 URL 写入元素前对其进行转换或过滤。",
  },
  "ai-reasoning": {
    isStreaming: "是否仍在接收推理过程。",
    duration: "已完成的推理耗时，单位为秒。",
    ...common,
  },
  avatar: {
    size: "头像尺寸。",
    ...common,
  },
  badge: {
    variant: "徽章的视觉样式，用于区分状态或语义。",
    size: "徽章的高度和左右内边距。",
    ...common,
  },
  bubble: {
    side: "消息气泡的水平对齐方向。",
  },
  button: {
    variant: "按钮的视觉样式。",
    size: "按钮的高度和内边距。设置为 icon 时用于仅显示图标的方形按钮。",
    ...common,
    motion:
      "是否启用轻微的弹性按压和悬停动效。开启 prefers-reduced-motion 时会自动停用。",
    ripple:
      "是否启用从指针位置向外扩散的点击涟漪效果。开启 prefers-reduced-motion 时会自动停用。",
  },
  dialog: {
    variant: "显示为居中的模态对话框，或在文档流中从触发元素原地展开。",
  },
  "morphing-dialog": {
    transition: "控制触发元素与对话框之间形变过程的弹簧或补间动画。",
  },
  "morphing-popover": {
    open: "受控模式下弹出层是否打开。",
    defaultOpen: "非受控模式下弹出层的初始打开状态。",
    onOpenChange: "弹出层打开状态变化时触发。",
    transition: "控制触发元素与弹出层之间形变过程的弹簧或补间动画。",
    variants: "配置内容展开和收起时使用的 Motion 动画变体。",
  },
  "progressive-blur": {
    direction: "模糊效果最强的一侧。",
    blurLayers: "叠加的遮罩层数量，小于 2 时会按 2 层处理。",
    blurIntensity: "每增加一层时叠加的模糊强度，单位为像素。",
  },
  watermark: {
    content: "要重复显示的一行或多行水印文字。",
    image: "重复显示的水印图片地址。设置后优先使用图片，不再使用 content。",
    rotate: "水印的顺时针旋转角度，单位为度。",
    gap: "水印单元之间的水平和垂直间距。",
    offset: "重复图案的水平和垂直偏移量。",
    width: "单个水印标记的宽度，单位为像素。",
    height: "单个水印标记的高度，单位为像素。",
    font: "水印文字的排版设置。",
    opacity: "水印图层的不透明度。",
    zIndex: "水印图层的堆叠层级。",
  },
  "confirm-dialog": {
    trigger: "打开对话框的触发元素。使用 asChild 时会直接渲染为该元素。",
    title: "对话框顶部显示的标题。",
    description: "标题下方显示的补充说明。",
    confirmLabel: "确认按钮的文字。",
    cancelLabel: "取消按钮的文字。",
    variant: "确认按钮的视觉样式。",
    onConfirm: "用户点击确认按钮时触发。",
  },
  motion: {
    preset: "入场动画的预设名称。",
    transition: "预设过渡动画，或自定义的 Motion Transition 配置。",
    delay: "开始播放动画前等待的时间，单位为秒。",
    inView: "是否在内容进入视口时播放动画，而不是挂载后立即播放。",
    once: "是否只在内容第一次进入视口时播放动画。",
    ...common,
  },
  icon: {
    icon: "要渲染的 Lucide 图标组件。",
    size: "图标尺寸名称，或精确的像素值。",
    variant: "图标使用的语义文字颜色。",
    color: "自定义 CSS/SVG 颜色。设置后会覆盖 variant。",
    label: "图标的无障碍名称。纯装饰图标无需设置。",
  },
  "animated-icon": {
    icon: "从 @animateicons/react/lucide 导入的路径动画图标。",
    label: "图标的无障碍名称。纯装饰图标无需设置。",
    ref: "由动态路径图标暴露的命令式播放控制句柄。",
    size: "图标尺寸，单位为像素。",
    duration: "图标支持时，单次动画的时长，单位为秒。",
    isAnimated: "是否播放图标动画，具体效果取决于图标本身是否支持。",
    variant: "图标使用的语义文字颜色。",
    color: "自定义 CSS/SVG 颜色。设置后会覆盖 variant。",
  },
  "shiny-button": {
    speed: "光带完整扫过按钮一次所需的时间，单位为秒。",
    gap: "两次光带扫过之间的停顿时间，单位为秒。",
    ...common,
  },
  switch: {
    size: "开关的尺寸。",
    ...common,
  },
  progress: {
    variant: "进度指示器的布局形式。",
    size: "线性进度条的厚度，或环形进度的直径。",
    color: "已完成部分使用的语义强调色。",
    showValue: "是否在环形进度中显示当前百分比。",
    indicatorClassName: "应用于已完成部分的额外 CSS 类名。",
    ...common,
  },
  slider: {
    variant: "轨道的默认或交互展开样式。",
    showValue: "控制数值标签的显示时机。",
    formatValue: "格式化滑块手柄上方显示的数值。",
    marks: "在轨道上显示为圆点的刻度值数组。",
    ...common,
  },
  "color-picker": {
    value: "当前颜色的 CSS OKLCH 值。",
    onValueChange: "颜色通道或完整颜色值变化时持续触发。",
    label: "颜色选择器触发按钮的无障碍名称。",
    showAlpha: "是否显示透明度通道。",
    swatches: "可供快速选择的 OKLCH 颜色。",
    ...common,
  },
  "radio-group": { ...common },
  checkbox: {
    size: "复选框的尺寸。",
    ...common,
  },
  select: { ...common },
  cascader: {
    options: "级联选项树。",
    value: "受控模式下当前选中的完整路径。",
    defaultValue: "非受控模式下初始选中的完整路径。",
    onValueChange: "选中路径变化时触发，并返回当前路径及对应选项。",
    placeholder: "未选择完整路径时显示的占位文本。",
    separator: "已选路径各层级之间显示的分隔符。",
    closeOnSelect: "选择叶子节点后是否自动关闭选项面板。",
    panelLabel: "选项面板的无障碍名称。",
    contentClassName: "应用于浮层面板的额外 CSS 类名。",
    renderValue: "自定义触发器中已选路径的渲染方式。",
    ...common,
  },
  form: {
    animated: "挂载表单时是否播放入场动效。",
    autoComplete: "是否启用浏览器的表单自动填充。",
    method: "提交表单时使用的 HTTP 方法。",
    target: "提交结果打开的浏览上下文。",
    acceptCharset: "提交表单使用的字符编码。",
    action: "表单提交的目标地址。",
    encType: "提交表单时使用的编码类型。",
    noValidate: "是否跳过浏览器原生表单校验。",
  },
  tabs: { ...common },
  navbar: {
    orientation: "导航栏方向。vertical 适合应用级左侧导航。",
    collapsed: "受控模式下垂直导航栏是否处于紧凑状态。",
    defaultCollapsed: "非受控模式下导航栏的初始紧凑状态。",
    onCollapsedChange: "垂直导航栏在展开和紧凑状态之间切换时触发。",
  },
  collapsible: { ...common },
  input: {
    variant: "输入框的外观样式。",
    visualSize: "输入框的视觉尺寸。",
    label: "输入框获得焦点或有值前显示在输入区域内的浮动标签。",
    startContent: "显示在输入内容前的装饰或操作内容。",
    endContent: "显示在输入内容后的装饰或操作内容。",
    wrapperClassName: "应用于最外层容器的额外 CSS 类名。",
    ...common,
  },
  textarea: {
    showCount: "是否在文本域右下角显示当前字符数。",
    resize: "用户可以拖动调整文本域尺寸的方向。",
    wrapperClassName: "应用于最外层容器的额外 CSS 类名。",
    ...common,
  },
  combobox: { ...common },
  toggle: {
    variant: "切换按钮的视觉样式。",
    size: "切换按钮的高度与内边距尺寸。",
    ...common,
  },
  "toggle-group": {
    variant: "组内切换按钮统一使用的视觉样式。",
    size: "组内切换按钮统一使用的高度与内边距尺寸。",
    ...common,
  },
  typography: {
    variant: "文本元素使用的语义层级与排版样式。",
  },
  "input-number": { ...common },
  "aspect-ratio": { ...common },
  "tree-select": { ...common },
  download: {
    filename: "控件中显示的文件名称。",
    meta: "文件类型、大小等补充信息。",
    fileIcon:
      "根据文件名推断的文件类型图标。传入节点可覆盖默认图标，传入 false 可隐藏图标。",
    href: "激活控件后下载的文件地址。",
    status: "下载流程的当前状态。",
    progress: "确定进度的下载进度，取值范围为 0 到 100。",
    size: "控件的高度和间距尺寸。",
    onDownload: "用户请求下载时触发。",
    ...common,
  },
  upload: {
    label: "拖放区域内显示的主要操作提示。",
    description: "主要提示下方显示的补充说明。",
    status: "上传流程的当前状态。",
    progress: "确定进度的上传进度，取值范围为 0 到 100。",
    size: "控件的高度和间距尺寸。",
    multiple: "是否允许一次选择多个文件。",
    accept: "允许选择的 MIME 类型或文件扩展名，多个值用逗号分隔。",
    onFilesChange: "选择或拖入文件时触发。",
    onUpload: "文件选择完成并更新内部上传状态后触发。",
    ...common,
  },
  kbd: { size: "键盘按键提示的尺寸。" },
  tooltip: {
    open: "受控模式下提示内容是否打开。",
    defaultOpen: "非受控模式下提示内容的初始打开状态。",
    onOpenChange: "提示内容打开状态变化时触发。",
    delayDuration: "鼠标悬停后显示提示的延迟时间，单位为毫秒。",
    disableHoverableContent:
      "指针离开触发元素后是否立即关闭提示，而不允许指针移入提示内容。",
  },
  "image-preview": {
    src: "缩略图和大图预览共用的图片地址。",
    alt: "图片的无障碍描述。",
    previewSrc: "仅用于大图预览的高清图片地址。",
    caption: "展开预览后显示在图片下方的说明文字。",
    open: "受控模式下预览是否打开。",
    defaultOpen: "非受控模式下预览的初始打开状态。",
    onOpenChange: "预览打开或关闭时触发。",
    minZoom: "允许使用的最小缩放比例。",
    maxZoom: "允许使用的最大缩放比例。",
    zoomStep: "每次缩放增加或减少的比例。",
    showToolbar: "是否显示缩放、旋转、重置和可选的下载操作。",
    downloadName: "下载时使用的文件名。设置后会显示下载操作。",
    thumbnailClassName: "应用于缩略图的额外 CSS 类名。",
    previewClassName: "应用于展开图片的额外 CSS 类名。",
    ...common,
  },
  skeleton: {
    shape: "占位骨架的圆角样式。",
    animation: "加载时使用的动画样式。",
  },
  alert: {
    variant: "提示的语义样式和默认图标。",
    size: "提示内容的密度尺寸。",
    title: "说明文字上方显示的可选标题。",
    icon: "自定义前置图标。传入 false 可隐藏图标。",
    action: "显示在提示末尾的可选操作。",
    closable: "是否显示关闭按钮。",
    visible: "受控模式下提示是否显示。",
    defaultVisible: "非受控模式下提示的初始显示状态。",
    onVisibleChange: "提示显示状态变化时触发。",
  },
  message: {
    position: "消息默认显示在屏幕上的位置。",
    duration: "消息默认显示时长，单位为毫秒。",
    maxCount: "同时显示的消息数量上限。超出后优先移除较早的消息。",
    offset: "消息与视口边缘的距离，单位为像素。",
    gap: "堆叠消息之间的间距，单位为像素。",
    stacked: "是否将消息重叠堆叠显示，而不是显示为纵向列表。",
    maxVisibleMessages: "堆叠队列中同时显示的最大层数。",
    scaleFactor: "每增加一层时应用的缩放幅度。",
    expandOnHover: "鼠标悬停或键盘聚焦时是否展开消息堆。",
    dragToDismiss: "是否允许通过水平拖动移除消息。",
    dragThreshold: "触发拖动移除所需的水平距离，单位为像素。",
    motion: "所有消息共用的动效配置。",
  },
  "in-view": {
    children: "进入视口时需要播放动画的内容。",
    variants: "内容隐藏和显示时使用的动画变体。",
    transition: "状态切换时使用的 Motion 过渡动画。",
    viewOptions: "Intersection Observer 配置，例如 margin 和 amount。",
    once: "是否只播放一次入场动画。",
    as: "组件实际渲染的 HTML 元素。",
  },
  "scroll-progress": {
    variant: "进度指示器的视觉形式。",
    position: "固定进度条所在的边缘。使用 inline 可让它保留在正常文档流中。",
    container: "要监听的滚动容器；未设置时监听页面。",
    target: "用于计算进度的目标元素。目标元素经过视口时会推动进度变化。",
    offset: "设置 target 后使用的 Motion 滚动偏移范围。",
    size: "环形指示器的直径，单位为像素。",
    strokeWidth: "环形指示器的描边宽度，单位为像素。",
    smooth: "是否使用弹簧平滑处理突然的滚动进度变化。",
    trackClassName: "应用于未完成轨道的 CSS 类名。",
    indicatorClassName: "应用于移动进度指示器的 CSS 类名。",
  },
  "smooth-scroll": {
    children: "要放入 Lenis 上下文或自定义滚动容器中的内容。",
    options: "Lenis 实例的配置。",
    disabled: "是否停用插值滚动，但保留内容包装结构。",
    respectReducedMotion: "是否遵循操作系统的减少动态效果偏好。",
    root: "是否在页面上初始化全局 Lenis 实例。",
    autoRaf: "是否自动使用 requestAnimationFrame 驱动 Lenis。",
  },
  parallax: {
    children: "随包装容器经过视口而产生位移的内容。",
    axis: "内容移动的方向。",
    distance: "从滚动开始到结束的位移范围，单位为像素。",
    scale: "可选的缩放范围，适合在画框中展示图片时使用。",
    container: "要监听的滚动容器；未设置时监听页面。",
    offset: "包装容器使用的 Motion 滚动偏移范围。",
  },
  "scroll-text": {
    children: "要按滚动进度控制显示效果的文字。",
    mode: "文字揭示方式。highlight 会将文字从弱化色逐步变为前景色。",
    per: "文字拆分的粒度：行、单词或字符。",
    as: "组件实际渲染的 HTML 元素。",
    range: "分配给全部文字片段的滚动进度范围。",
    overlap: "相邻文字片段之间重叠的进度范围。",
    container: "要监听的滚动容器；未设置时监听页面。",
    offset: "文字区块使用的 Motion 滚动偏移范围。",
    segmentClassName: "应用于每个文字片段的 CSS 类名。",
  },
  "sticky-stack": {
    children: "按堆叠顺序渲染的 StickyStackItem 元素。",
    top: "第一个粘性项目距离顶部的偏移量，单位为像素。",
    gap: "堆叠项目之间仍可见的垂直偏移量，单位为像素。",
    scaleStep: "每有一张卡片位于当前项目上方时减少的缩放比例。",
    container: "要监听的滚动容器；未设置时监听页面。",
  },
  "horizontal-scroll": {
    children: "区块固定时沿水平方向移动的宽内容。",
    container: "要监听的滚动容器；未设置时监听页面。",
    scrollPadding: "额外增加的垂直滚动距离，单位为像素。",
    viewportClassName: "应用于固定视口的 CSS 类名。",
    trackClassName: "应用于水平移动轨道的 CSS 类名。",
  },
  "velocity-marquee": {
    children: "在无缝轨道中重复显示的内容。",
    baseSpeed: "静止滚动时轨道的速度，单位为每秒像素数。",
    sensitivity: "滚动速度每增加一个单位时，轨道额外增加的速度。",
    maxBoost: "由滚动速度带来的最大加速值，单位为每秒像素数。",
    gap: "重复内容组之间的间距。",
    reverse: "是否反转基础滚动方向和跟随滚动的方向。",
    container: "要监听的滚动容器；未设置时监听页面。",
    groupClassName: "应用于每个重复内容组的 CSS 类名。",
  },
  "scroll-expand": {
    children: "固定视口中随滚动展开或收拢的媒体或首屏内容。",
    direction: "视觉变换跟随的滚动方向。",
    inset: "紧凑状态下四条边的初始内缩比例。",
    radius: "紧凑状态下的圆角半径，单位为像素。",
    scrollLength: "区块占用的视口高度数量。",
    container: "要监听的滚动容器；未设置时监听页面。",
    viewportClassName: "应用于固定视口的 CSS 类名。",
    frameClassName: "应用于变换内容画框的 CSS 类名。",
  },
  "scroll-sequence": {
    children: "固定视口中按顺序逐个显示的步骤内容。",
    stepLength: "每次切换占用的滚动距离，以视口高度为单位。",
    container: "要监听的滚动容器；未设置时监听页面。",
    showProgress: "是否显示紧凑的步骤指示器。",
    onStepChange: "当前步骤变化时触发。",
    viewportClassName: "应用于固定视口的 CSS 类名。",
    stepClassName: "应用于当前步骤包装元素的 CSS 类名。",
  },
  "scroll-snap": {
    axis: "滚动吸附的方向。",
    strictness: "浏览器是否必须最终停在某个吸附点上。",
    hideScrollbar: "是否隐藏原生滚动条，同时保留滚动能力。",
  },
  "infinite-slider": {
    children: "在持续循环轨道中显示的内容。",
    gap: "各项内容之间的间距，单位为像素。",
    speed: "轨道移动速度，单位为每秒像素数。",
    speedOnHover: "鼠标悬停时的轨道速度。设置为 0 可在悬停时暂停。",
    direction: "滑块移动的方向。",
    reverse: "是否反转移动方向。",
  },
  cursor: {
    children: "显示在指针位置的视觉内容。",
    springConfig: "跟随指针移动时使用的弹簧参数。",
    attachToParent: "是否将指针视觉限制在组件父元素范围内。",
    transition: "指针视觉进入和离开时使用的过渡动画。",
    variants: "指针视觉的初始、播放中和离开状态。",
    hideNativeCursor: "激活区域内是否隐藏系统原生指针。",
    onPositionChange: "指针坐标变化时触发。",
  },
  magnetic: {
    strength: "内容跟随指针移动的强度。",
    maxDistance: "任一方向允许移动的最大距离，单位为像素。",
    springConfig: "内容移动和回弹时使用的弹簧参数。",
    disabled: "是否停用指针跟随，同时保留原有布局。",
  },
  glow: {
    children: "显示在发光边缘上方的内容。",
    variant: "发光边缘的视觉样式。",
    color: "solid 样式使用的 CSS 颜色。",
    colors: "沿彩虹边缘分布的颜色列表。",
    spread: "光线超出边缘的距离，单位为像素。",
    borderWidth: "发光边缘的宽度，单位为像素。",
    glowOpacity: "发光效果的最大不透明度。",
    pulse: "是否让 solid 样式缓慢呼吸。",
    duration: "一次发光动画循环的时长，单位为秒。",
  },
  annotation: {
    children: "显示在标注线条上方的行内内容。",
    variant: "标注线条的形状。",
    color: "标注线条的颜色。",
    duration: "线条扫过内容一次所需的时间，单位为秒。",
    delay: "开始高亮前等待的时间，单位为秒。",
    inView: "是否在内容进入视口时开始高亮。",
    once: "是否只在内容第一次进入视口时高亮。",
  },
  "slide-swap": {
    children: "同时用于离场和入场图层的内容。",
    direction: "当前可见图层离场的方向。",
    active: "是否从组件外部强制切换到交换状态。",
    transition: "两个内容图层共用的过渡动画。",
  },
  "hover-marquee": {
    children: "列表行未激活时显示的内容。",
    marquee: "浮入预览轨道中循环显示的内容。",
    speed: "预览轨道移动速度，单位为每秒像素数。",
    gap: "重复预览项之间的间距，单位为像素。",
    reverse: "是否反转预览轨道的移动方向。",
    active: "是否从组件外部强制打开预览。",
    marqueeClassName: "应用于移动预览层的 CSS 类名。",
  },
  "spotlight-card": {
    children: "显示在指针聚光效果上方的内容。",
    radius: "聚光区域的半径，单位为像素。",
    color: "聚光中心使用的 CSS 颜色。",
    spotlightClassName: "应用于聚光图层的 CSS 类名。",
  },
  "tilt-card": {
    children: "显示在 3D 倾斜平面上的内容。",
    maxTilt: "任一方向允许的最大旋转角度，单位为度。",
    perspective: "透视深度，单位为像素。",
    hoverScale: "指针悬停在卡片上时使用的缩放比例。",
    glare: "是否显示随指针移动的高光图层。",
    glareClassName: "应用于可选高光图层的 CSS 类名。",
  },
  "image-trail": {
    items: "指针移动时依次循环显示的视觉内容。",
    children: "交互区域内始终显示的静态内容。",
    distance: "新增一项轨迹内容前指针需要移动的距离，单位为像素。",
    lifetime: "每项轨迹内容的显示时长，单位为毫秒。",
    maxItems: "同时渲染的轨迹内容数量上限。",
    itemClassName: "应用于每个定位轨迹项的 CSS 类名。",
  },
  "hover-preview": {
    children: "触发预览的交互行、链接或控件。",
    preview: "显示在指针旁边的预览内容。",
    offsetX: "预览相对指针的水平偏移量，单位为像素。",
    offsetY: "预览相对指针的垂直偏移量，单位为像素。",
    open: "受控模式下预览是否显示。",
    previewClassName: "应用于浮动预览的 CSS 类名。",
  },
  "aurora-background": {
    children: "显示在极光图层上方的前景内容。",
    colors: "移动光场使用的三个 CSS 颜色。",
    duration: "完整移动一轮所需的时间，单位为秒。",
    blur: "光场的模糊强度，单位为像素。",
    layerClassName: "应用于每个极光图层的 CSS 类名。",
  },
  "grain-overlay": {
    opacity: "颗粒图层的不透明度。",
    frequency: "基础湍流频率。",
    octaves: "分形噪声的叠加层数。",
    seed: "用于生成可复现噪声的随机种子。",
    blendMode: "遮罩图层使用的 CSS 混合模式。",
  },
  "spotlight-grid": {
    children: "显示在网格图案上方的内容。",
    pattern: "要显示的背景图案。",
    size: "图案单元格的尺寸，单位为像素。",
    radius: "指针聚光区域的半径，单位为像素。",
    patternColor: "图案使用的 CSS 颜色。",
    baseOpacity: "始终显示的基础图案不透明度。",
    patternClassName: "应用于两层图案的 CSS 类名。",
  },
  "text-effect": {
    children: "要拆分并播放动画的文本。",
    per: "文本拆分粒度：行、单词或字符。",
    as: "组件实际渲染的 HTML 元素。",
    preset: "内置的片段入场动画。",
    variants: "自定义容器和文本片段的动画变体。",
    delay: "开始揭示文本前等待的时间，单位为秒。",
    trigger: "是否显示文本。切换为 false 可隐藏文本。",
    speedReveal: "容器交错动画速度的倍率。",
    speedSegment: "每个文本片段动画速度的倍率。",
    segmentWrapperClassName: "应用于每个文本片段包装元素的额外 CSS 类名。",
    containerTransition: "容器使用的自定义过渡动画。",
    segmentTransition: "每个文本片段使用的自定义过渡动画。",
    onAnimationStart: "文本揭示动画开始时触发。",
    onAnimationComplete: "文本揭示动画完成时触发。",
  },
  "text-loop": {
    children: "按顺序逐个显示的文本或行内内容。",
    interval: "两项内容之间的切换间隔，单位为秒。",
    transition: "每项内容使用的 Motion 过渡动画。",
    variants: "内容的初始、播放中和离场动画状态。",
    onIndexChange: "当前内容索引变化后触发。",
    trigger: "是否自动开始循环切换。",
    mode: "AnimatePresence 使用的动画排队模式。",
  },
  "text-morph": {
    children: "字符位置发生变化时需要进行形变的文字。",
    as: "组件实际渲染的 HTML 元素。",
  },
  "text-roll": {
    children: "按字符逐个翻滚显示的文字。",
    duration: "每个字符完成一次翻滚所需的时间，单位为秒。",
    getEnterDelay: "计算每个字符进入翻滚状态延迟的函数。",
    getExitDelay: "计算每个字符回到静止状态延迟的函数。",
    transition: "合并到每个字符上的过渡动画。",
    variants: "每个字符轨道的静止和悬停状态。",
    trigger: "是否在悬停时播放，或在挂载后立即播放。",
  },
  "text-scramble": {
    children: "通过扰码效果最终显示的目标文字。",
    as: "组件实际渲染的 HTML 元素。",
    duration: "完整揭示文字所需的时间，单位为秒。",
    speed: "两次扰码帧之间的间隔，单位为秒。",
    characterSet: "扰码过程中随机抽取的字符集合。",
    trigger: "是否播放扰码效果。先切换为 false 再切换为 true 可重新播放。",
    onScrambleComplete: "每个字符都解析为最终值后触发。",
  },
  "text-shimmer": {
    children: "承载扫光效果的文字。",
    as: "组件实际渲染的 HTML 元素。",
    duration: "高光完整扫过一次所需的时间，单位为秒。",
    spread: "高光渐变相对文字宽度的范围。",
  },
  "text-shimmer-wave": {
    children: "按字符播放立体波浪动画的文字。",
    as: "组件实际渲染的 HTML 元素。",
    duration: "完整波浪动画循环的时长，单位为秒。",
    zDistance: "字符沿 Z 轴移动的距离，单位为像素。",
    xDistance: "字符沿水平方向移动的距离，单位为像素。",
    yDistance: "字符沿垂直方向移动的距离，单位为像素。",
    spread: "相邻字符波浪相位之间的距离。",
    scaleDistance: "字符达到的最大缩放比例。",
    rotateYDistance: "字符达到的最大 Y 轴旋转角度，单位为度。",
    transition: "合并到每个字符上的过渡动画。",
  },
  "sliding-number": {
    value: "要显示的数字或数字字符串。",
    padStart: "是否为一位整数补充前导零。",
    decimalSeparator: "替代小数点显示的字符。",
    transition: "每个数字滚轮使用的过渡动画。",
  },
  table: {
    containerClassName: "应用于横向滚动容器的额外 CSS 类名。",
    density: "控制单元格内边距和行高。",
    striped: "是否为表格主体的交替行添加浅色背景。",
    stickyHeader: "表格容器滚动时是否保持表头可见。",
  },
  calendar: {
    value: "当前选中的日期。",
    defaultValue: "非受控模式下初始选中的日期。",
    onValueChange: "用户选择日期时触发。",
    month: "当前显示的月份。",
    defaultMonth: "非受控模式下初始显示的月份。",
    onMonthChange: "用户切换月份导致显示月份变化时触发。",
    min: "允许选择的最早日期。",
    max: "允许选择的最晚日期。",
    disabled: "用于判断日期是否禁用的匹配函数。",
    showOutsideDays: "是否显示当前月份前后相邻月份的日期。",
    locale: "格式化月份标题时使用的地区设置。",
  },
  "date-picker": {
    value: "当前选中的日期。",
    defaultValue: "非受控模式下初始选中的日期。",
    onValueChange: "选择或清除日期后触发。",
    placeholder: "没有选中日期时显示的占位文本。",
    locale: "格式化日期时使用的地区设置。",
    formatOptions: "传递给 Intl.DateTimeFormat 的日期格式化选项。",
    clearable: "是否允许清除当前日期。",
    min: "允许选择的最早日期。",
    max: "允许选择的最晚日期。",
    disabledDate: "用于判断日期是否禁用的匹配函数。",
    ...common,
  },
  "time-picker": {
    value: "当前选中的时间，格式为 24 小时制 HH:mm。",
    defaultValue: "非受控模式下初始选中的时间。",
    onValueChange: "时间变化时触发，并返回 24 小时制 HH:mm 值。",
    hourCycle: "时间显示使用 12 小时制还是 24 小时制。",
    minuteStep: "分钟选择的间隔。",
    placeholder: "没有选中时间时显示的占位文本。",
    ...common,
  },
  kanban: {
    onMove: "卡片被拖入其他列后触发。",
  },
  timeline: {
    orientation: "时间线的排列方向。",
    align: "内容相对时间线的对齐方式。交错对齐仅在纵向布局中生效。",
    density: "事件之间的间距尺寸。",
    connector: "连接线的视觉样式。",
  },
  "empty-state": {
    size: "空状态内容的垂直密度。",
  },
  spin: {
    spinning: "是否显示加载状态。",
    size: "加载指示器的尺寸。",
    label: "显示在加载指示器旁边的无障碍提示文字。",
    indicator: "替换默认的轨道式加载指示器。",
    delay: "显示加载指示器前等待的时间，避免快速操作出现闪烁。",
    fullscreen: "是否覆盖整个视口，而不是在文档流中渲染。",
  },
  "notification-badge": {
    count: "提示标记中显示的内容。传入数字时会受 max 限制。",
    max: "显示数字前允许的最大值，超过后显示带加号的最大值。",
    showZero: "数值为 0 时是否仍显示标记。",
    dot: "是否显示小圆点，而不是显示 count 内容。",
    visible: "受控模式下提示标记是否显示。",
    variant: "提示标记使用的语义颜色。",
    offset: "标记相对右上角锚点的像素偏移量。",
    label: "提示标记的无障碍名称。",
  },
  drawer: {
    open: "受控模式下抽屉是否打开。",
    defaultOpen: "非受控模式下抽屉的初始打开状态。",
    onOpenChange: "抽屉请求改变显示状态时触发。",
    modal: "是否锁定焦点并禁止与抽屉外部内容交互。",
  },
  descriptions: {
    title: "描述列表上方显示的标题。",
    extra: "显示在标题相对位置的操作内容。",
    columns: "每行显示的描述项组数。",
    bordered: "是否为标签和值绘制结构化边框。",
    layout: "标签显示在值的旁边还是上方。",
    size: "描述列表的垂直密度。",
    labelWidth: "横向布局中每个标签单元格的固定宽度。",
  },
  card: {
    variant: "卡片的表面样式。",
    interactive: "卡片作为整体可操作时，是否显示按压反馈。",
  },
}

export function getPropDescription(
  component: string,
  prop: string,
  sourceDescription?: string
): string | undefined {
  return (
    PropDescriptions[component]?.[prop] ??
    sourceDescription?.trim() ??
    undefined
  )
}
