import { promises as fs } from "node:fs"
import path from "node:path"
import ts from "typescript"
import type * as docgen from "react-docgen-typescript"
import type {
  PlaygroundConfig,
  PlaygroundControl,
  PlaygroundSourceEdit,
  PlaygroundTarget,
  PlaygroundValue,
} from "../lib/playground-types"
import { getPropDescription } from "../lib/prop-descriptions"

const ROOT = process.cwd()
const banner =
  "// AUTO-GENERATED by scripts/build-playgrounds.mts — do not edit by hand.\n"
const nativeProps = new Set([
  "className",
  "disabled",
  "placeholder",
  "readOnly",
  "maxLength",
  "value",
  "checked",
  "open",
  "defaultValue",
  "defaultChecked",
  "defaultOpen",
  "orientation",
  "required",
  "size",
])
const excluded = new Set([
  "asChild",
  "as",
  "ref",
  "key",
  "children",
  "forceMount",
  "autoFocus",
  "fullscreen",
  "root",
])
const nodeText = new Set([
  "title",
  "description",
  "label",
  "prefix",
  "suffix",
  "emptyText",
  "loadingText",
])
const nativeDescriptions: Record<string, string> = {
  className: "组件的 CSS 类名。",
  disabled: "是否禁用组件。",
  placeholder: "内容为空时显示的提示。",
  readOnly: "是否只允许读取内容。",
  maxLength: "允许输入的最大字符数。",
  value: "当前值。",
  checked: "当前选中状态。",
  open: "是否打开浮层。",
  defaultValue: "初始值，修改后会重新加载预览。",
  defaultChecked: "初始选中状态。",
  defaultOpen: "初始打开状态。",
  orientation: "排列方向。",
  required: "是否必填。",
}

async function write(file: string, content: string) {
  try {
    if ((await fs.readFile(file, "utf8")) === content) return
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
  }
  await fs.writeFile(file, content, "utf8")
}

function staticValue(
  node: ts.Node | undefined,
  bindings: Map<string, ts.Expression>,
  visiting = new Set<string>()
): PlaygroundValue | undefined {
  if (!node) return undefined
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node))
    return node.text
  if (ts.isNumericLiteral(node)) return Number(node.text)
  if (node.kind === ts.SyntaxKind.TrueKeyword) return true
  if (node.kind === ts.SyntaxKind.FalseKeyword) return false
  if (node.kind === ts.SyntaxKind.NullKeyword) return null
  if (
    ts.isAsExpression(node) ||
    ts.isTypeAssertionExpression(node) ||
    ts.isParenthesizedExpression(node) ||
    ts.isSatisfiesExpression(node)
  )
    return staticValue(node.expression, bindings, visiting)
  if (
    ts.isPrefixUnaryExpression(node) &&
    node.operator === ts.SyntaxKind.MinusToken
  ) {
    const value = staticValue(node.operand, bindings, visiting)
    return typeof value === "number" ? -value : undefined
  }
  if (
    ts.isIdentifier(node) &&
    bindings.has(node.text) &&
    !visiting.has(node.text)
  ) {
    return staticValue(
      bindings.get(node.text),
      bindings,
      new Set([...visiting, node.text])
    )
  }
  if (ts.isArrayLiteralExpression(node)) {
    const values = node.elements.map((element) =>
      staticValue(element, bindings, visiting)
    )
    return values.every((value) => value !== undefined)
      ? (values as PlaygroundValue[])
      : undefined
  }
  if (ts.isObjectLiteralExpression(node)) {
    const value: Record<string, PlaygroundValue> = {}
    for (const property of node.properties) {
      if (
        !ts.isPropertyAssignment(property) ||
        ts.isComputedPropertyName(property.name)
      )
        return undefined
      const next = staticValue(property.initializer, bindings, visiting)
      if (next === undefined) return undefined
      value[property.name.getText().replace(/^['"]|['"]$/g, "")] = next
    }
    return value
  }
  return undefined
}

function deriveControl(
  item: string,
  prop: docgen.PropItem,
  initialValue?: PlaygroundValue
): PlaygroundControl | undefined {
  if (excluded.has(prop.name) || /^on[A-Z]/.test(prop.name)) return undefined
  if (
    prop.parent?.fileName.includes("node_modules") &&
    !nativeProps.has(prop.name)
  )
    return undefined
  const raw =
    prop.type.name === "enum"
      ? (prop.type.raw ?? prop.type.name)
      : prop.type.name
  if (/=>/.test(raw) || /Ref<|RefObject|ElementType/.test(raw)) return undefined
  const type = raw.replace(/\s*\|\s*(undefined|null)/g, "").trim()
  const literals = raw
    .match(/"[^"]*"|'[^']*'/g)
    ?.map((value) => value.slice(1, -1))
  let control: PlaygroundControl["control"]
  let options: string[] | undefined
  let numericOptions = false
  if (type === "boolean" || type === "true" || type === "false")
    control = "boolean"
  else if (type === "number") control = "number"
  else if (type === "string") control = "text"
  else if (/^\d+(\s*\|\s*\d+)*$/.test(type)) {
    control = "select"
    options = type.split(/\s*\|\s*/)
    numericOptions = true
  } else if (literals?.length && !/\bstring\b/.test(type)) {
    control = "select"
    options = [...new Set(literals)]
  } else if (
    /ReactNode/.test(type) &&
    nodeText.has(prop.name) &&
    (initialValue === undefined || typeof initialValue === "string")
  )
    control = "text"
  else if (
    initialValue !== undefined &&
    typeof initialValue === "object" &&
    initialValue !== null &&
    JSON.stringify(initialValue).length < 16000
  )
    control = "json"
  else return undefined
  let defaultValue: string | undefined
  if (
    prop.defaultValue != null &&
    ["select", "text", "number", "boolean"].includes(control)
  ) {
    const candidate = String(prop.defaultValue.value).replace(
      /^['"]|['"]$/g,
      ""
    )
    if (
      (control !== "number" || Number.isFinite(Number(candidate))) &&
      (control !== "select" || options?.includes(candidate)) &&
      (control !== "boolean" || ["true", "false"].includes(candidate))
    )
      defaultValue = candidate
  }
  const result: PlaygroundControl = {
    name: prop.name,
    type: raw,
    required: prop.required,
    control,
    description:
      getPropDescription(item, prop.name, prop.description) ||
      nativeDescriptions[prop.name],
    ...(options ? { options } : {}),
    ...(numericOptions ? { numericOptions: true } : {}),
    ...(defaultValue !== undefined ? { defaultValue } : {}),
    ...(initialValue !== undefined ? { initialValue } : {}),
  }
  if (control === "number") {
    result.step =
      /duration|delay|speed|gap|scale|opacity|stiffness|damping|mass|amount|intensity/i.test(
        prop.name
      )
        ? 0.1
        : 1
    if (
      /duration|delay|speed|height|width|size|radius|count|maxLength|stagger|blur|gap|offset|step/i.test(
        prop.name
      )
    )
      result.min = /speed|height|width|maxLength|step/i.test(prop.name)
        ? 0.1
        : 0
    if (/opacity|scaleFactor|threshold/.test(prop.name)) {
      result.min = 0
      result.max = 1
      result.step = 0.05
    }
    if (prop.name === "decimalPlaces") {
      result.min = 0
      result.max = 20
      result.step = 1
    }
  }
  return result
}

function applyEdits(
  source: string,
  edits: Array<{ start: number; end: number; text: string }>
) {
  for (const edit of edits.sort((a, b) => b.start - a.start))
    source = source.slice(0, edit.start) + edit.text + source.slice(edit.end)
  return source
}

export async function buildDemoPlaygrounds(
  docsByFile: Map<string, docgen.ComponentDoc[]>,
  items: Array<{ name: string; files: Array<{ path: string }> }>,
  standalone: Record<string, PlaygroundConfig>
) {
  const directory = path.join(ROOT, "registry", "playgrounds")
  await fs.mkdir(directory, { recursive: true })
  const configs: Record<string, PlaygroundConfig> = {}
  const entries: string[] = []
  const issues: string[] = []
  for (const folder of ["components", "charts"]) {
    for (const filename of (
      await fs.readdir(path.join(ROOT, "content/docs", folder))
    ).filter((file) => file.endsWith(".mdx"))) {
      const mdx = await fs.readFile(
        path.join(ROOT, "content/docs", folder, filename),
        "utf8"
      )
      const name = /^component:\s*(.+)$/m.exec(mdx)?.[1].trim()
      if (!name) continue
      if (standalone[name]) {
        const item = items.find((item) => item.name === name)!
        entries.push(
          `  ${JSON.stringify(name)}: React.lazy(() => import("@/${item.files[0].path.replace(/\.tsx?$/, "")}").then((module) => ({ default: module.${standalone[name].exportName} }))),`
        )
        continue
      }
      const preview = /<ComponentPreview\s+name="([^"]+)"([^>]*?)\/>/.exec(mdx)
      if (!preview) {
        issues.push(`${name}: missing primary example`)
        continue
      }
      const demo = preview[1]
      const source = await fs.readFile(
        path.join(ROOT, "registry/examples", `${demo}.tsx`),
        "utf8"
      )
      const file = ts.createSourceFile(
        `${demo}.tsx`,
        source,
        ts.ScriptTarget.Latest,
        true,
        ts.ScriptKind.TSX
      )
      const item = items.find((item) => item.name === name)!
      const imported = new Map<string, string>()
      const docs = docsByFile.get(path.resolve(ROOT, item.files[0].path)) ?? []
      const bindings = new Map<string, ts.Expression>()
      const modifications: Array<{ start: number; end: number; text: string }> =
        []
      const sourceEdits: PlaygroundSourceEdit[] = []
      const targets: PlaygroundTarget[] = []
      const wrappers: string[] = []
      let directProps = false
      const counts = new Map<string, number>()
      for (const statement of file.statements) {
        if (
          !ts.isImportDeclaration(statement) ||
          !ts.isStringLiteral(statement.moduleSpecifier)
        )
          continue
        if (
          statement.moduleSpecifier.text !==
          `@/${item.files[0].path.replace(/\.tsx?$/, "")}`
        )
          continue
        const imports = statement.importClause?.namedBindings
        if (imports && ts.isNamedImports(imports))
          for (const specifier of imports.elements) {
            if (!specifier.isTypeOnly)
              imported.set(
                specifier.name.text,
                (specifier.propertyName ?? specifier.name).text
              )
          }
      }
      function collectBindings(node: ts.Node) {
        if (ts.isVariableDeclaration(node) && node.initializer) {
          if (ts.isIdentifier(node.name))
            bindings.set(node.name.text, node.initializer)
          if (
            ts.isArrayBindingPattern(node.name) &&
            ts.isCallExpression(node.initializer) &&
            /useState$/.test(node.initializer.expression.getText(file))
          ) {
            const first = node.name.elements[0]
            if (
              first &&
              ts.isBindingElement(first) &&
              ts.isIdentifier(first.name) &&
              node.initializer.arguments[0]
            ) {
              bindings.set(first.name.text, node.initializer.arguments[0])
            }
          }
        }
        ts.forEachChild(node, collectBindings)
      }
      collectBindings(file)
      function visit(node: ts.Node) {
        if (ts.isJsxElement(node) || ts.isJsxSelfClosingElement(node)) {
          const opening = ts.isJsxElement(node) ? node.openingElement : node
          const localName = opening.tagName.getText(file)
          const exportName = imported.get(localName)
          const doc = docs.find((doc) => doc.displayName === exportName)
          if (doc) {
            const count = counts.get(localName) ?? 0
            counts.set(localName, count + 1)
            const id = `${exportName}:${count}`
            const attrs = new Map(
              opening.attributes.properties
                .filter(ts.isJsxAttribute)
                .map((attr) => [attr.name.getText(file), attr])
            )
            const controls = Object.values(doc.props)
              .map((prop) => {
                const attr = attrs.get(prop.name)
                const init =
                  attr &&
                  (!attr.initializer
                    ? true
                    : ts.isJsxExpression(attr.initializer)
                      ? staticValue(attr.initializer.expression, bindings)
                      : staticValue(attr.initializer, bindings))
                return deriveControl(name!, prop, init)
              })
              .filter((control): control is PlaygroundControl =>
                Boolean(control)
              )
              .filter(
                (control) =>
                  !(
                    ["accordion", "toggle-group"].includes(name!) &&
                    control.name === "type"
                  )
              )
            if (controls.length) {
              const events: Record<string, string> = {}
              const candidates: Record<string, string[]> = {
                value: ["onValueChange", "onChange"],
                open: ["onOpenChange"],
                checked: ["onCheckedChange"],
                pressed: ["onPressedChange"],
                activeId: ["onActiveChange"],
                size: ["onSizeChange"],
                index: ["onIndexChange"],
              }
              for (const control of controls) {
                const event = candidates[control.name]?.find(
                  (event) => doc.props[event]
                )
                if (event) events[control.name] = event
              }
              targets.push({
                id,
                label: `${exportName}${count ? ` · ${count + 1}` : ""}`,
                exportName: exportName!,
                controls,
                events,
                nativeEvents: Object.values(events).filter((event) =>
                  /ChangeEvent|FormEvent/.test(doc.props[event].type.name)
                ),
              })
              if (
                ["StickyStackItem", "DescriptionsItem"].includes(exportName!)
              ) {
                directProps = true
                modifications.push({
                  start: opening.attributes.end,
                  end: opening.attributes.end,
                  text: ` {...getPlaygroundProps(${JSON.stringify(id)})}`,
                })
              } else {
                const wrapper = `Playground${localName}${count}`
                wrappers.push(
                  `const ${wrapper} = withPlaygroundProps(${localName}, ${JSON.stringify(id)})`
                )
                modifications.push({
                  start: opening.tagName.getStart(file),
                  end: opening.tagName.end,
                  text: wrapper,
                })
                if (ts.isJsxElement(node))
                  modifications.push({
                    start: node.closingElement.tagName.getStart(file),
                    end: node.closingElement.tagName.end,
                    text: wrapper,
                  })
              }
              for (const control of controls) {
                const attr = attrs.get(control.name)
                if (attr) {
                  const initializer =
                    attr.initializer && ts.isJsxExpression(attr.initializer)
                      ? attr.initializer.expression
                      : undefined
                  const binding =
                    initializer && ts.isIdentifier(initializer)
                      ? bindings.get(initializer.text)
                      : undefined
                  sourceEdits.push({
                    target: id,
                    prop: control.name,
                    start: attr.getStart(file),
                    end: attr.end,
                    kind: "jsx",
                    ...(binding
                      ? {
                          binding: {
                            start: binding.getStart(file),
                            end: binding.end,
                          },
                        }
                      : {}),
                  })
                }
              }
              sourceEdits.push({
                target: id,
                start: opening.attributes.end,
                end: opening.attributes.end,
                kind: "jsx",
              })
            }
          }
        }
        ts.forEachChild(node, visit)
      }
      visit(file)

      // Confetti's primary example calls the public function rather than JSX.
      if (name === "confetti") {
        const id = "fireConfetti:0"
        const declarations = ts.createSourceFile(
          "confetti-options.ts",
          await fs.readFile(path.join(ROOT, item.files[0].path), "utf8"),
          ts.ScriptTarget.Latest,
          true
        )
        const options = declarations.statements.find(
          (node): node is ts.InterfaceDeclaration =>
            ts.isInterfaceDeclaration(node) &&
            node.name.text === "ConfettiOptions"
        )!
        const controls: PlaygroundControl[] = []
        for (const member of options.members) {
          if (
            !ts.isPropertySignature(member) ||
            !member.type ||
            !ts.isIdentifier(member.name)
          )
            continue
          const type = member.type.getText(declarations)
          if (
            !["number", "boolean"].includes(type) ||
            ["ticks", "zIndex"].includes(member.name.text)
          )
            continue
          const docs = ts
            .getJSDocCommentsAndTags(member)
            .map((node) => node.getText(declarations))
            .join(" ")
          const value = /@default\s+([\d.]+|true|false)/.exec(docs)?.[1]
          controls.push({
            name: member.name.text,
            type,
            required: false,
            control: type === "boolean" ? "boolean" : "number",
            description: docs
              .replace(/^\/\*\*\s*|\s*\*\/$/g, "")
              .replace(/@default.*$/, "")
              .trim(),
            defaultValue: value,
            min:
              type === "number" && member.name.text !== "drift" ? 0 : undefined,
            step: ["decay", "gravity", "scalar"].includes(member.name.text)
              ? 0.05
              : 1,
          })
        }
        targets.push({
          id,
          label: "fireConfetti",
          exportName: "fireConfetti",
          controls,
          events: {},
        })
        const importNode = file.statements.find(
          (node): node is ts.ImportDeclaration =>
            ts.isImportDeclaration(node) &&
            ts.isStringLiteral(node.moduleSpecifier) &&
            node.moduleSpecifier.text.endsWith("/confetti")
        )!
        const imports = importNode.importClause!
          .namedBindings as ts.NamedImports
        const specifier = imports.elements.find(
          (item) => item.name.text === "fireConfetti"
        )!
        modifications.push({
          start: specifier.getStart(file),
          end: specifier.end,
          text: "fireConfetti as originalFireConfetti",
        })
        const fn = file.statements.find(
          (node): node is ts.FunctionDeclaration =>
            ts.isFunctionDeclaration(node) &&
            Boolean(
              node.modifiers?.some(
                (modifier) => modifier.kind === ts.SyntaxKind.DefaultKeyword
              )
            )
        )!
        modifications.push({
          start: fn.body!.getStart(file) + 1,
          end: fn.body!.getStart(file) + 1,
          text: `\n  const fireConfetti = usePlaygroundFunction(originalFireConfetti, ${JSON.stringify(id)})\n`,
        })
        function calls(node: ts.Node) {
          if (
            ts.isCallExpression(node) &&
            node.expression.getText(file) === "fireConfetti" &&
            node.arguments[0] &&
            ts.isObjectLiteralExpression(node.arguments[0])
          ) {
            const object = node.arguments[0]
            for (const member of object.properties)
              if (
                ts.isPropertyAssignment(member) &&
                controls.some(
                  (control) => control.name === member.name.getText(file)
                )
              )
                sourceEdits.push({
                  target: id,
                  prop: member.name.getText(file),
                  start: member.getStart(file),
                  end: member.end,
                  kind: "object",
                  group: object.getStart(file),
                })
            sourceEdits.push({
              target: id,
              start: object.properties.at(-1)?.end ?? object.getStart(file) + 1,
              end: object.properties.at(-1)?.end ?? object.getStart(file) + 1,
              kind: "object",
              group: object.getStart(file),
            })
          }
          ts.forEachChild(node, calls)
        }
        calls(file)
      }
      if (!targets.length) {
        issues.push(`${name}: no adjustable props in ${demo}`)
        continue
      }
      const lastImport = file.statements.filter(ts.isImportDeclaration).at(-1)!
      const imports =
        name === "confetti"
          ? "usePlaygroundFunction"
          : `withPlaygroundProps${directProps ? ", usePlaygroundProps" : ""}`
      if (directProps) {
        const fn = file.statements.find(
          (node): node is ts.FunctionDeclaration =>
            ts.isFunctionDeclaration(node) &&
            Boolean(
              node.modifiers?.some(
                (modifier) => modifier.kind === ts.SyntaxKind.DefaultKeyword
              )
            )
        )!
        modifications.push({
          start: fn.body!.getStart(file) + 1,
          end: fn.body!.getStart(file) + 1,
          text: "\n  const getPlaygroundProps = usePlaygroundProps()\n",
        })
      }
      modifications.push({
        start: lastImport.end,
        end: lastImport.end,
        text: `\nimport { ${imports} } from "@/components/playground-context"\n\n${wrappers.join("\n")}\n`,
      })
      const adapter = `"use client"\n\n${banner}${applyEdits(source, modifications)}`
      await write(path.join(directory, `${name}.tsx`), adapter)
      const primary =
        targets.find((target) =>
          target.controls.some((control) => control.name !== "className")
        ) ?? targets[0]
      // Keep the first meaningful component selected rather than a structural wrapper.
      targets.splice(targets.indexOf(primary), 1)
      targets.unshift(primary)
      configs[name] = {
        exportName: primary.exportName,
        demo,
        targets,
        sourceEdits,
        previewClassName: /previewClassName="([^"]+)"/.exec(preview[2])?.[1],
      }
      entries.push(
        `  ${JSON.stringify(name)}: React.lazy(() => import("@/registry/playgrounds/${name}")),`
      )
    }
  }
  if (issues.length)
    throw new Error(`Incomplete playground coverage:\n${issues.join("\n")}`)
  await write(
    path.join(ROOT, "registry/__playground-config__.ts"),
    `${banner}import type { PlaygroundConfig } from "@/lib/playground-types"\n\nexport const DemoPlaygrounds: Record<string, PlaygroundConfig> = ${JSON.stringify(configs, null, 2)}\n`
  )
  await write(
    path.join(ROOT, "registry/__playground__.tsx"),
    `${banner}"use client"\n\nimport * as React from "react"\n\n// eslint-disable-next-line @typescript-eslint/no-explicit-any\nexport const Playgrounds: Record<string, React.ComponentType<any>> = {\n${entries.join("\n")}\n}\n`
  )
  return entries.length
}
